import axios from "axios";
import { config } from "@/config";
import { logger } from "@/utils/logger";

export class GeminiService {
  private static readonly MODEL = "imagen-3.0-generate-001";
  private static readonly BASE_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GeminiService.MODEL}:predict`;

  /**
   * Generates an image using Google Gemini (Imagen) API.
   * @param prompt The text prompt for image generation.
   * @returns Base64 encoded image data.
   */
  public static async generateImage(prompt: string): Promise<string> {
    const apiKey = config.gemini.apiKey;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not configured in the environment.");
    }

    const url = `${this.BASE_URL}?key=${apiKey}`;

    try {
      logger.info(`[GeminiService] Generating image with prompt: "${prompt.substring(0, 100)}..."`);
      
      const response = await axios.post(url, {
        instances: [{ prompt }],
        parameters: { 
          sampleCount: 1,
          aspectRatio: "1:1",
          outputMimeType: "image/png"
        }
      }, {
        timeout: 60000 // 60 seconds timeout for image generation
      });

      const predictions = response.data?.predictions;
      if (!predictions || predictions.length === 0) {
        throw new Error("No image was generated by Gemini API.");
      }

      const base64Data = predictions[0]?.bytesBase64Encoded;
      if (!base64Data) {
        throw new Error("Image data (bytesBase64Encoded) is missing in Gemini API response.");
      }

      return base64Data;
    } catch (error: any) {
      const errorMessage = error.response?.data?.error?.message || error.message;
      logger.error(`[GeminiService] Generation failed: ${errorMessage}`);
      throw new Error(`Gemini Image Generation Failed: ${errorMessage}`);
    }
  }
}
